### ISSUE TITLE
Label & background are not displayed

### ISSUE THREAD

**Issue by BC17** [lrsjng/jquery-qrcode#17]
Hello dear and thank for your work

I can't figure out how to display my text label and image background

var img_codebar = document.createElement('img')
img_codebar.src = "img/codebar.jpg"

$(div_codebar).qrcode({label : 'QR-certificat', fontname: 'Arial', fontcolor: 'white',text : 'text'', size : 100, render:"canvas", fill : "black", background : img_codebar, quiet: 1});

This give me a QR with a transparent background and no label

Can you help?

**Comment by lrsjng** [comment]
@BC17 can't reproduce this at the moment..

**Comment by yanzixiang** [comment]
same here....
no label showes.
and how to config the label font size?

**Comment by b354c502** [comment]
same problem here... the label is not generated.

**Comment by lrsjng** [comment]
@BC17 @yanzixiang @b354c502 did you set `mode` to `1` or `2`?

label size is specified with `mSize` as relative text height. `0.2` means 20% of QR Code height.
please have a look at the *Options* section on the [project page](https://larsjung.de/jquery-qrcode/).

**Comment by hawkeas** [comment]
Hi:
Thank your work!!
A problem is here ! I am using qr code, when two-dimensional code can be generated, but the middle of the logo image for the first time and can not display refresh can display pictures obtained through HTTP access, then turn base64.
![image](https://cloud.githubusercontent.com/assets/13267283/11837948/ec4171ca-a41e-11e5-982d-74deeea5ed38.png)
![image](https://cloud.githubusercontent.com/assets/13267283/11837960/ffb5f7da-a41e-11e5-8566-28a2e413acb9.png)
![image](https://cloud.githubusercontent.com/assets/13267283/11837970/0f55c60c-a41f-11e5-9ec0-1a0cae844328.png)

HELP!!! HOW, I CAN FIX IT??? THANKS!!

**Comment by yanzixiang** [comment]
after add {mode:2} to the options,
I got the label displayed,
but my label is very long,
after it is rendered on the QR canvas,
my phone can NOT scan the QR,
how can I render the label under the QR canvas ?

**Comment by bhoylloza** [comment]
@BC17 can't reproduce this at the moment
