### ISSUE TITLE
With Render type 'div' the lable is not displayed 

### ISSUE THREAD

**Issue by pranaysharma** [lrsjng/jquery-qrcode#19]
Hi,
In render type 'div' the label is not displayed.
The same can be seen in your demo at :http://larsjung.de/jquery-qrcode/latest/demo/
I am not sure if this is normal or a bug.
Anyways many thanks for your code.
It is really helpful :)

**Comment by lrsjng** [comment]
@pranaysharma label and images are only supported in the `canvas` and `image` mode
