### ISSUE TITLE
doesn't show image-box?

### ISSUE THREAD

**Issue by jetz** [lrsjng/jquery-qrcode#20]
Hi, I do as #16 , but the chrome & safari doesn't show the image box in generated qrcode,  leaving blank, firefox is ok. After page loaded, exec the function  in console of dev tools, then chrome  & safari will show as expected. 

Is the plugin's order important or did I miss something?

**Comment by lrsjng** [comment]
@jetz the image must be completely loaded before its data can be used..

**Comment by jetz** [comment]
@lrsjng thx for your help, I solve this problem by using `$(window).load(function() {...});)` instead of `$(document).ready(function() {...});` (abbr. `$(function(){...});` )

**Comment by sunflower-tc** [comment]
have sample question And i also use $(window).load

**Comment by marlonnardi** [comment]
Other solution

```
 var img_buffer = new Image();
 img_buffer.src = 'https://store.falconsistemas.com.br/imagens/componentes/fsqrcode/tunifsqrcode.png' ;
 img_buffer.onload = function() {
    $('#qrcode').qrcode({
                            render: "canvas",
                            mode: 4,  
                            size: 165,
                            text: "abcdefghijklmnopqrstuvwxyz0123456789",
                            image:  img_buffer  });
 }
```
