### ISSUE TITLE
Ability to Save to SVG Instead of a PNG

### ISSUE THREAD

**Issue by KrisB1022** [lrsjng/jquery-qrcode#21]
I'm looking for a way to save the file as a SVG using a download a tag if possible.

I'd like to generate the QR, download and use it for print, however, I've been unable to find a way to do that.

I understand that doing that with the canvas element is not possible.

**Comment by lrsjng** [comment]
@KrisB1022 SVG mode is not included right now. But you can use `image` mode with a high resolution (e.g. 1200px) and download/print the image..
