### ISSUE TITLE
Is there typedef file for typescript?

### ISSUE THREAD

**Issue by Galiabu** [lrsjng/jquery-qrcode#24]
Hi,
Is there any chance for providing .d.ts file for this code for typescript usage?
Thanks,
Galia

**Comment by danmana** [comment]
Created typedef d.ts definition. See pull request https://github.com/borisyankov/DefinitelyTyped/pull/6424

**Comment by danmana** [comment]
This can be closed. Pull request was merged. See borisyankov/DefinitelyTyped/issues/6292
