### ISSUE TITLE
 The middle of the logo image for the first time and can not display refresh can display pictures

### ISSUE THREAD

**Issue by ghost** [lrsjng/jquery-qrcode#26]
Hi:
Thank your work!!
A problem is here ! I am using qr code, when two-dimensional code can be generated, but the middle of the logo image for the first time and can not display refresh can display pictures obtained through HTTP access, then turn base64.  And I used on  Android and IOS device!!
![image](https://cloud.githubusercontent.com/assets/13267283/11837948/ec4171ca-a41e-11e5-982d-74deeea5ed38.png)
![image](https://cloud.githubusercontent.com/assets/13267283/11837960/ffb5f7da-a41e-11e5-8566-28a2e413acb9.png)
![image](https://cloud.githubusercontent.com/assets/13267283/11837970/0f55c60c-a41f-11e5-9ec0-1a0cae844328.png)

HELP!!! HOW, I CAN FIX IT??? THANKS!!

**Comment by lrsjng** [comment]
@hawkeas you have to wait until the image is loaded, before you can use it

**Comment by hawkeas** [comment]
@lrsjng  thank you！！ But I hava used the " img.onload = function() {...}  ", here did this, is not right???

**Comment by rxwangwb** [comment]
请问怎么设置image选项呢？
`image:'20170402164722_IMG_0112.JPG'`

**Comment by bhoylloza** [comment]
Hi:
Thank your work!!
A problem is here ! I am using qr code, when two-dimensional code can be generated, but the middle of the logo image for the first time and can not display refresh can display pictures obtained through HTTP access, then turn base64. And I used on Android and IOS device!!
image
image
image

HELP!!! HOW, I CAN FIX IT??? THANKS!!

**Comment by bhoylloza** [comment]
请问怎么设置image选项呢？
image:'20170402164722_IMG_0112.JPG'
