### ISSUE TITLE
QRCode for unicode characters ?

### ISSUE THREAD

**Issue by Quadratica** [lrsjng/jquery-qrcode#29]
Hallo lars,

i would like to know how, language such as Chinese, Japanese, Arabic etc, are treated in order by produce the QR Code.
For example, before start to generate the QR Code, is Japanise (or Chinese etc) text converted to unicode character escape sequences ?
E.g. these are 2 Japanise character: \u3092\u30c0

I need this information to estimate a threshold value in my algorithm.

Cheers,
 F

**Comment by bhoylloza** [comment]
Hallo lars,

i would like to know how, language such as Chinese, Japanese, Arabic etc, are treated in order by produce the QR Code.
For example, before start to generate the QR Code, is Japanise (or Chinese etc) text converted to unicode character escape sequences ?
E.g. these are 2 Japanise character: \u3092\u30c0

I need this information to estimate a threshold value in my algorithm.

Cheers,
F

**Comment by lrsjng** [comment]
I don't think it's using escape sequences, but have a look yourself here: https://github.com/lrsjng/jquery-qrcode/blob/master/vendor/qrcode_UTF8.js#L24
