### ISSUE TITLE
Looking to just use an existing image for the image option

### ISSUE THREAD

**Issue by mchupp** [lrsjng/jquery-qrcode#32]
Have a little trouble with it. What would the syntax be and does the image need to be converted to base64?  

Thanks!

**Comment by mchupp** [comment]
Found it. Just passed in: 
image: document.getElementById("img-buffer")

**Comment by rxwangwb** [comment]
Did you know how to set the image option?
`<div id = "qrcodeid"></div> `

`$("#qrcodeid").qrcode({
    // render method: 'canvas', 'image' or 'div'
    render: 'canvas',

    // version range somewhere in 1 .. 40
    minVersion: 1,
    maxVersion: 40,

    // error correction level: 'L', 'M', 'Q' or 'H'
    ecLevel: 'L',

    // offset in pixel if drawn onto existing canvas
    left: 0,
    top: 0,

    // size in pixel
    size: 200,

    // code color or image element
    fill: '#000',

    // background color or image element, null for transparent background
    background: null,

    // content
    text: 'some text',

    // corner radius relative to module width: 0.0 .. 0.5
    radius: 0,

    // quiet zone in modules
    quiet: 0,

    // modes
    // 0: normal
    // 1: label strip
    // 2: label box
    // 3: image strip
    // 4: image box
    mode: 0,

    mSize: 0.1,
    mPosX: 0.5,
    mPosY: 0.5,

    label: 'no label',
    fontname: 'sans',
    fontcolor: '#000',

    image: null
});`

I tried set the image like this:

`image:'20170402164722_IMG_0112.JPG'`

but it didn't work.

**Comment by rxwangwb** [comment]
I also tried this:
`<div id = "qrcodeid"><img src="lehu.png" id="qrcodeimage"></div> `

And image option:
`image: document.getElementById("qrcodeimage")`

**Comment by ssunbob** [comment]
Well I find the solution : 
In the http structure
`<div id="qrcodeCanvas" class="text-center"></div>
<img id="img-buffer" class="hidden" src="pathto/img/abc.jpg">`
In the jquery options: 
`mode:4, 
image:document.getElementById("img-buffer")`

**Comment by bhoylloza** [comment]
Did you know how to set the image option?
<div id = "qrcodeid"></div>

$("#qrcodeid").qrcode({ render: 'canvas', minVersion: 1, maxVersion: 40, ecLevel: 'L', left: 0, top: 0, size: 200, fill: '#000', background: null, text: 'some text', radius: 0, quiet: 0, mode: 0, mSize: 0.1, mPosX: 0.5, mPosY: 0.5, label: 'no label', fontname: 'sans', fontcolor: '#000', image: null });

I tried set the image like this:

image:'20170402164722_IMG_0112.JPG'

but it didn't work.

**Comment by bhoylloza** [comment]
Found it. Just passed in:
image: document.getElementById("img-buffer")

**Comment by bhoylloza** [comment]
I also tried this:
<div id = "qrcodeid"><img src="lehu.png" id="qrcodeimage"></div>

And image option:
image: document.getElementById("qrcodeimage")

But it still not work.

**Comment by bhoylloza** [comment]
Well I find the solution :
In the http structure
<div id="qrcodeCanvas" class="text-center"></div> <img id="img-buffer" class="hidden" src="pathto/img/abc.jpg">
In the jquery options:
mode:4, image:document.getElementById("img-buffer")
