### ISSUE TITLE
Not available on bower anymore

### ISSUE THREAD

**Issue by theunexpected1** [lrsjng/jquery-qrcode#33]
Bower repo for `jquery-qrcode` points to [gcusnieux/jquery-qrcode](https://github.com/gcusnieux/jquery-qrcode)

**Comment by turristan** [comment]
@theunexpected1 try `bower install --save lrsjng/jquery-qrcode`

**Comment by bhoylloza** [comment]
@theunexpected1 try bower install --save lrsjng/jquery-qrcode
