### ISSUE TITLE
Main bower filename mistake

### ISSUE THREAD

**Issue by egogg** [lrsjng/jquery-qrcode#35]
Bower main file of bower.json
`"main": "dist/jquery.qrcode.js"`
should be:
`"main": "dist/jquery-qrcode.js"`

or change the filename of dist js.

**Comment by bhoylloza** [comment]
Bower main file of bower.json
"main": "dist/jquery.qrcode.js"
should be:
"main": "dist/jquery-qrcode.js"

or change the filename of dist js.
