### ISSUE TITLE
Not support AMD Specification

### ISSUE THREAD

**Issue by TechQuery** [lrsjng/jquery-qrcode#36]
Dear author, why not follow **jQuery** to support [the best Module Specification of Web Front-End](https://github.com/amdjs/amdjs-api/wiki/AMD) ?

It makes coding easier for developers & users~

**Comment by bhoylloza** [comment]
Dear author, why not follow jQuery to support the best Module Specification of Web Front-End ?

It makes coding easier for developers & users~

**Comment by lrsjng** [comment]
AMD should be supported now (since 86948f725f5ae4d78c45735d5c92070fd67e9b99)
