### ISSUE TITLE
GS1 qrcode specification

### ISSUE THREAD

**Issue by prtome** [lrsjng/jquery-qrcode#37]
Is it possible to generate the GS1 qrcode? I have tried to manually encode the FNCs but it does not seem to work ( i am most certainly  doing it wrong). 
thanks

**Comment by bhoylloza** [comment]
Is it possible to generate the GS1 qrcode? I have tried to manually encode the FNCs but it does not seem to work ( i am most certainly doing it wrong).
thanks

**Comment by lrsjng** [comment]
It's only designed to encode simple text at the moment. sry.
