### ISSUE TITLE
Rgb/rgba values for colours break img check 

### ISSUE THREAD

**Issue by timolehto** [lrsjng/jquery-qrcode#38]
`jq(colorsetting).is('img')` breaks if color is a string `rgb(4,5,56)` or `rgba(5,5,5,0.5)`, but the actual drawing does support this so there's no reason to prevent it.

**Comment by bhoylloza** [comment]
jq(colorsetting).is('img') breaks if color is a string rgb(4,5,56) or rgba(5,5,5,0.5), but the actual drawing does support this so there's no reason to prevent it

**Comment by bhoylloza** [comment]
#39 Fixes Rgb/rgba values for colours break img check

**Comment by timolehto** [comment]
@bhoylloza are you some sort of a bot? What are those weird commit sha comments in the PR? Why are you duplicating my comments?

**Comment by lrsjng** [comment]
Fixed in upcoming release.
