### ISSUE TITLE
Can't Make It Working!

### ISSUE THREAD

**Issue by vdanelia** [lrsjng/jquery-qrcode#40]
Hello please help, can't make it working...
I downloaded the script, integrated it to my site... opened created qrcode design, Now how to insert that qrcode into my pages?

Another Question: How to make qr code to Automatically generate page url where I'll insert the qrcode?

Thank you In advanced!

**Comment by bhoylloza** [comment]
Hello please help, can't make it working...
I downloaded the script, integrated it to my site... opened created qrcode design, Now how to insert that qrcode into my pages?

Another Question: How to make qr code to Automatically generate page url where I'll insert the qrcode?

Thank you In advanced!

**Comment by lrsjng** [comment]
it's a jQuery plugin, you need to use jQuery to generate the qrcodes. There is no other automation supported, sry.
