### ISSUE TITLE
The web browser said that "Cannot read property 'naturalWidth' of null" !

### ISSUE THREAD

**Issue by CharlesWuQiushi** [lrsjng/jquery-qrcode#44]
I wrote my own file to generate QR code. I'm a Chinese, so some of the code comment may not be displayed
.
The JS code is like this: 
`<script>
        'use strict';
        //写入二维码生成函数
        function GenerateQR() {
            //清空结果展示页面
            document.getElementById("result-display").innerHTML = "";
            //进行二维码值对应生成
            $('#result-display').empty().qrcode(
                {
                    render: "canvas",
                    text: document.getElementById("info-text").value,
                    ecLevel: "H",
                    size: value,
                    fill: document.getElementById("colorpicker-value").value,
                    background: "#ffffff",
                    typeNumber: -1,
                    radius: parseInt($("#info-radius").val(), 10) * 0.005,
                    quiet: quite,
                    mode: QRmode,
                    mSize: parseInt(document.getElementById("info-mSize").value) / 100,
                    mPosX: 50,
                    mPosY: 50,
                    image: $("LOGOimg")[0]
                }
            );
        }

        //在二维码内容字符数超出300时，进行提示
        document.getElementById("info-text-length-display").style.display = "inline";
        function CheckTypeOfQR() {
            if (document.getElementById("info-text").value.length >= 300) {
                document.getElementById("info-text-length-warning").style.display = "inline";
                document.getElementById("info-text-length-display").style.color = "#f8b600";
                if (document.getElementById("info-text").value.length >= 400 && document.getElementById("info-text").value.length < 550) {
                    document.getElementById("info-text-length-display").style.color = "#f87000";
                } else if (document.getElementById("info-text").value.length >= 550) {
                    document.getElementById('info-text-length-display').style.color = "red";
                } else {
                    document.getElementById("info-text-length-display").style.color = "#00dd12";
                }
            } else {
                document.getElementById("info-text").maxlength = "";
                document.getElementById("info-text-length-warning").style.display = "none";
                document.getElementById("info-text-length-display").style.color = "#00dd12";
            }
        }

        //二维码内容为“网址”时，在文本前添加“http://”
        document.getElementById("type-setting-url").onclick = function () {
            if (!document.getElementById("info-text").value.includes("http")) {
                document.getElementById("info-text").value = "http://";
            }
        }

        document.getElementById("type-setting-text").onclick = function () {
            document.getElementById("info-text").value = "";
        }

        //写入二维码宽度及拖动条改变函数
        var value, radius, quite = 1, mSize = 0.18;
        var QRmode = 0;
        value = $('#info-width').val() * 4 + 100;
        $('#info-width-display').html(value.toFixed(1));
        $('#info-width').css({
            "background-size": (value - 100) / 4 + "% 100%"
        })
        function ChangeWidth() {
            value = $('#info-width').val();
            var valStr = value + "% 100%";
            $('#info-width-display').html((value * 4 + 100).toFixed(1));
            $('#info-width').css({
                "background-size": valStr
            })
            $("input[name='info-width']").val((value * 1).toFixed(1));
            value = value * 4 + 100;
            if (value >= 375) {
                document.getElementById("info-width-warning").style.display = "inline-block";
            } else {
                document.getElementById("info-width-warning").style.display = "none";
            }
        }

        //写入码点圆滑程度改变函数
        $('#info-radius').css({
            "background-size": "0% 0%"
        })
        $("input[name='info-radius']").val("0");

        function ChangeRadius() {
            radius = $('#info-radius').val();
            var valStrOfRadius = radius + "% 100%";
            $('#info-radius-display').html((radius * 1).toFixed(1));
            $('#info-radius').css({
                "background-size": valStrOfRadius
            })
            $("input[name='info-radius']").val((radius * 1).toFixed(1));
            radius *= 0.5;
            if (radius >= 30) {
                document.getElementById("info-radius-warning").style.display = "inline-block";
            } else {
                document.getElementById("info-radius-warning").style.display = "none";
            }
        }

        //写入二维码空白区域变化函数
        $('#info-quite').css({
            "background-size": $('#info-quite').val() + "% 100%"
        })
        function ChangeQuiteSize() {
            quite = $('#info-quite').val();
            var valStrOfQuite = quite + "% 100%";
            $('#info-quite-display').html((quite / 20).toFixed(0));
            $('#info-quite').css({
                "background-size": valStrOfQuite
            })
            quite /= 20;
        }

        //写入二维码图片图片尺寸改变函数
        $('#info-mSize').css({
            "background-size": $('#info-mSize').val() + "% 100%"
        })
        function ChangeMSize() {
            mSize = $('#info-mSize').val();
            var valStrOfmSize = mSize + "% 100%";
            $('#info-mSize-display').html((mSize / 1).toFixed(0) + "%");
            $('#info-mSize').css({
                "background-size": valStrOfmSize
            })
            mSize /= 100;
        }

        //写入二维码生成总集成函数
        var guiValuePairs = [
            ['size', 'px'],
            ['minversion', ''],
            ['quiet', ' modules'],
            ['radius', '%'],
            ['msize', '%'],
            ['mposx', '%'],
            ['mposy', '%']
        ];

        function OnImageInput() {
            var input = $('#upload-file')[0];
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (event) {
                    $('#LOGOimg').attr('src', event.target.result);
                    QRmode = 4;
                    setTimeout(GenerateQR(), 250);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        function download() {
            $('#download').attr('href', $('#container canvas')[0].toDataURL('image/png'));
        }

        //将颜色选择input框中的值进行改变
        document.getElementById("info-fgcolor").value = "#000000";
        //对input背景颜色进行调整
        document.getElementById("info-fgcolor").style.backgroundColor = "#000000";
        document.getElementById("info-fgcolor").style.color = "#ffffff";

        function ChangeFGValue() {
            //将颜色选择input框中的值进行改变
            document.getElementById("info-fgcolor").value = document.getElementById("colorpicker-value").value;
            //将值变为全大写模式
            document.getElementById("colorpicker-value").value = document.getElementById("colorpicker-value").value;
            //对input背景颜色进行调整
            document.getElementById("info-fgcolor").style.backgroundColor = document.getElementById("colorpicker-value").value;
            //对input框背景颜色十六进制值进行判断，如果在取整为10进制值后小于8000000，则改变字体颜色
            if (parseInt(document.getElementById("colorpicker-value").value.replace("#", ""), 16) < 8000000) {
                document.getElementById("info-fgcolor").style.color = "white";
            } else {
                document.getElementById("info-fgcolor").style.color = "black";
            }
        }

        //当enter键按下时，进行二维码生成
        document.onkeydown = function (e) {
            if (e.keyCode == 13 && document.getElementById("info-text").value != "") {
                GenerateQR();
            }
        }

        //写入二维码生成集成函数
        function init() {
            $('#upload-file').on('change', OnImageInput);
            $('input, textarea, select').on('input change', GenerateQR());
            $(window).load(GenerateQR());
            CheckTypeOfQR();
            document.getElementById("info-text-length-display").innerText = "  " + document.getElementById("info-text").value.length + " / 750";
            GenerateQR();
        }
        $(init);

    </script>`
I have tried to attach a file to the page, but the result is:
![screenshot](https://user-images.githubusercontent.com/35140448/47264461-567b0880-d54a-11e8-9453-51858a44ece6.png)
[Issue-Upload.zip](https://github.com/lrsjng/jquery-qrcode/files/2498923/Issue-Upload.zip)
Please reply me after you found the solution. thank you for your patient!

**Comment by bhoylloza** [comment]
Issue-Upload.zip

**Comment by lrsjng** [comment]
"Cannot read property 'naturalWidth' of null" most likely means you want to render a image, that you didn't specified in the options.
