### ISSUE TITLE
Render mode text

### ISSUE THREAD

**Issue by KenjiTakeuchi** [lrsjng/jquery-qrcode#46]
If possible, I am looking for a way to save text format QR data files.

I want to generate QR and use text data, but I could not find that way.

I need to print the QR code on the ReWrite card.

Example）

11111110001000110011001111111
10000010111001110000101000001
10111010100000001100101011101
10111010010010110010001011101
10111010111011111110101011101
10000010101010010011101000001
11111110101010101010101111111
00000000101100010100100000000
11010011000111000000101110110
00001001110110001000111001001
11010111000110001011111111110
01000101111111100010111001110
00110110001101000100011001011
11010000010101000001110000100
00010011100100000000101100111
10111001110101001101011011010
01101010111010010101110001010
10101100110011000100011000001
01111110110110000010011101011
11001000100010010110101000011
01001111110001111000111110100
00000000110100001101100010111
11111110110001001110101010010
10000010010001001010100010101
10111010010011011110111111000
10111010101111000000011011010
10111010011010100000100011101
10000010110011000101101010010
11111110100111100100110110010

**Comment by lrsjng** [comment]
Please use https://github.com/kazuhikoarase/qrcode-generator directly for this.
